---
hostname: cfr3.lab

mgmt_ip: 10.10.5.4
router_id: 3.3.3.3
router_iso: 49.0030.0300.3003.00

interfaces:
  - name: GigabitEthernet0/0/0/0
    peer: cfr3.lab
    ip_address: 172.16.0.14
  - name: GigabitEthernet0/0/0/1
    peer: cfr4.lab
    ip_address: 172.16.0.10
