all:
  children:
    iosxr:
      hosts:
        cfr3.lab:
          ansible_user: ubuntu
        cfr4.lab:
          ansible_user: ubuntu
    junos:
      hosts:
        cfr1.lab:
          ansible_user: ubuntu
        cfr2.lab:
          ansible_user: ubuntu
    ungrouped: {}
