---

- name: register current date
  shell: /bin/date +%Y%m%d%H%M%S
  register: date
  changed_when: False

- name: check for candidate file
  stat:
    path: '{{ candidate_dir }}/{{ inventory_hostname }}/candidate.conf'
    get_md5: no
    get_checksum: no
  register: candidate_file_st

- block:
  - include: commit-juniper.yml
    when: ansible_network_os  == 'junos'

  - include: commit-napalm.yml
    when: ansible_network_os  == 'iosxr'

  - name: remove candidate config
    file: path={{ candidate_dir }}/{{ inventory_hostname }} state=absent
    changed_when: False
    delegate_to: localhost
  when: candidate_file_st.stat.exists
