---
#
# These tasks are included in service_config_tasks-1.yml ( I know )
# Generate device config for each endpoint defined in the customer service-model
#
- set_fact:
    svc_template: "templates/iosxr/l2circuit.j2"
  when: loc.value.target_device.make == 'iosxr'
- set_fact:
    svc_template: "templates/junos/l2circuit.j2"
  when: loc.value.target_device.make == 'junos'
- set_fact:
    target_device_dir: "/etc/ansible/service-configs/{{ loc.value.target_device.name }}"

- template:
    src: "{{ svc_template }}"
    dest: "{{ target_device_dir }}/{{ svc.customer }}-{{ loc.key }}.conf"
